CREATE TABLE USERS (
    ID           BIGINT       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    LOGIN_ID     VARCHAR(128) NOT NULL,
    NAME         VARCHAR(128) NOT NULL,
    MAIL_ADDRESS VARCHAR(256),
    CONSTRAINT USERS_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_UK1 UNIQUE (LOGIN_ID)
);
